[package]
name = "graphql_test"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
serde = { version = "1", features = ["derive"] }
tai64 = { version = "4.0.0", features = ["serde"] }
bs58 = "0.4.0"