[package]
name = "governance-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
governance-core = { path = "../governance-core" }
csv = "1.1.6"
clap = { version = "4.0.18", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
