rusk_address = "https://devnet.nodes.dusk.network:8585"
prover_address = "https://provers.dusk.network:8686"
graphql_address = "http://devnet.nodes.dusk.network:9500/graphql"
gas_limit = 2_900_000_000
gas_price = 1
